# -------- Stage 1: Build --------
FROM ubuntu AS build

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --break-system-packages --no-cache-dir -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy app code
COPY . .

# -------- Stage 2: Runtime --------
FROM gcr.io/distroless/python3

WORKDIR /app

# Copy Python installed packages
COPY --from=build /usr/local/lib/python3.*/dist-packages /usr/local/lib/python3.*/dist-packages

# Copy app code
COPY --from=build /app /app

EXPOSE 5000

CMD ["app.py"]